import React from 'react'
import Header from '../Header'
import Footer from '../Footer'
import Head from 'next/head'
import styles from './Layout.module.css'

export default function Layout() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header/>
    <main className={styles.main}>

    </main>
    <Footer/>
    </>
  )
}
